--创建文件组
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M1
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M2
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M3
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M4
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M5
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M6
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M7
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M8
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M9
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M10
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M11
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_1_M12

Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M1
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M2
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M3
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M4
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M5
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M6
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M7
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M8
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M9
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M10
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M11
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_2_M12

Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M1
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M2
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M3
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M4
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M5
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M6
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M7
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M8
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M9
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M10
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M11
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_3_M12

Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M1
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M2
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M3
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M4
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M5
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M6
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M7
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M8
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M9
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M10
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M11
Alter database iCMSDB add filegroup T_DATA_TEMPE_DEVICE_MSITEDATA_4_M12


Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M1
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M2
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M3
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M4
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M5
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M6
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M7
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M8
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M9
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M10
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M11
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_1_M12

Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M1
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M2
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M3
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M4
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M5
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M6
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M7
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M8
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M9
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M10
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M11
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_2_M12

Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M1
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M2
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M3
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M4
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M5
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M6
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M7
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M8
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M9
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M10
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M11
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_3_M12

Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M1
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M2
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M3
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M4
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M5
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M6
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M7
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M8
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M9
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M10
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M11
Alter database iCMSDB add filegroup T_DATA_TEMPE_WS_MSITEDATA_4_M12


Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M1
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M2
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M3
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M4
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M5
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M6
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M7
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M8
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M9
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M10
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M11
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_1_M12

Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M1
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M2
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M3
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M4
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M5
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M6
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M7
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M8
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M9
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M10
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M11
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_2_M12

Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M1
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M2
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M3
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M4
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M5
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M6
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M7
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M8
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M9
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M10
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M11
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_3_M12

Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M1
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M2
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M3
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M4
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M5
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M6
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M7
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M8
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M9
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M10
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M11
Alter database iCMSDB add filegroup T_DATA_VOLTAGE_WS_MSITEDATA_4_M12


Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M1
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M2
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M3
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M4
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M5
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M6
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M7
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M8
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M9
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M10
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M11
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_VEL_M12


Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M1
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M2
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M3
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M4
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M5
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M6
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M7
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M8
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M9
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M10
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M11
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ACC_M12


Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M1
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M2
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M3
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M4
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M5
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M6
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M7
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M8
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M9
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M10
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M11
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_ENVL_M12


Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M1
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M2
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M3
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M4
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M5
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M6
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M7
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M8
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M9
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M10
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M11
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_DISP_M12


Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M1
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M2
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M3
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M4
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M5
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M6
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M7
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M8
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M9
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M10
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M11
Alter database iCMSDB add filegroup T_DATA_VIBRATING_SIGNAL_CHAR_HIS_LQ_M12


Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M1
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M2
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M3
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M4
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M5
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M6
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M7
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M8
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M9
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M10
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M11
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_1_M12

Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M1
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M2
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M3
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M4
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M5
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M6
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M7
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M8
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M9
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M10
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M11
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_2_M12

Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M1
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M2
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M3
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M4
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M5
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M6
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M7
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M8
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M9
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M10
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M11
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_3_M12

Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M1
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M2
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M3
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M4
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M5
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M6
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M7
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M8
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M9
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M10
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M11
Alter database iCMSDB add filegroup T_DATA_SPEED_DEVICE_MSITEDATA_4_M12